name: Multi-Tmate with Discord Webhook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-tmate-sessions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session_count: [1, 2, 3, 4, 5]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install tmate and dependencies
      run: |
        sudo apt update
        sudo apt install -y tmate curl jq
        
    - name: Generate SSH key for tmate
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/tmate_key -N ""
        
    - name: Start tmate session
      run: |
        tmate -S /tmp/tmate${{ matrix.session_count }}.sock new-session -d
        tmate -S /tmp/tmate${{ matrix.session_count }}.sock wait tmate-ready
        
    - name: Get tmate connection info
      run: |
        TMATE_SSH=$(tmate -S /tmp/tmate${{ matrix.session_count }}.sock display -p '#{tmate_ssh}')
        echo "TMATE_SSH=$TMATE_SSH" >> $GITHUB_ENV
        echo "$TMATE_SSH" > /tmp/tmate_${{ matrix.session_count }}.txt
        
    - name: Send to Discord Webhook
      run: |
        TMATE_SSH=$(cat /tmp/tmate_${{ matrix.session_count }}.txt)
        
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"content\": \"🎯 **Tmate Session ${{ matrix.session_count }}**\\n\\n**SSH Connection:**\\n\\`\\`\\`bash\\n$TMATE_SSH\\n\\`\\`\\`\\n\\n📅 Created: $(date)\n🔗 Session: ${{ matrix.session_count }} of 5\"}" \
        https://discord.com/api/webhooks/1433727858806624327/WDuONWA8t99ZEaTvhGXVNJ-M3wwm9ehbaJBzy00EYeA1m5u0mg6RJJtnCTmgUzT6l6ZX
      
    - name: Display success message
      run: |
        echo "✅ Tmate session ${{ matrix.session_count }} created and sent to Discord!"
        
  proxy-integration:
    runs-on: ubuntu-latest
    needs: create-tmate-sessions
    
    steps:
    - name: Fetch working proxies
      run: |
        curl -s "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all" > proxies.txt
        
        echo "🔄 Testing proxies..."
        while read proxy; do
          if timeout 5 curl -x "http://$proxy" -s http://httpbin.org/ip >/dev/null 2>&1; then
            echo "$proxy" >> working_proxies.txt
        done < proxies.txt
        
        echo "✅ Found $(wc -l < working_proxies.txt) working proxies!"
        
    - name: Send proxy summary to Discord
      run: |
        WORKING_COUNT=$(wc -l < working_proxies.txt 2>/dev/null || echo "0")
        
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"content\": \"🔧 **Proxy Summary**\\n\\nWorking Proxies: $WORKING_COUNT\\n\\n🚀 All tmate sessions created successfully!\", \"embeds\": [{\"title\": \"Multi-Tmate Setup Complete\", \"description\": \"✅ 5 tmate sessions created\\n🔄 $WORKING_COUNT working proxies found\\n\\n📊 **Ready for use!**\"}]}" \
        https://discord.com/api/webhooks/1433727858806624327/WDuONWA8t99ZEaTvhGXVNJ-M3wwm9ehbaJBzy00EYeA1m5u0mg6RJJtnCTmgUzT6l6ZX
